### PR TITLE
Merge Test Stuff

### PR DESCRIPTION
**Pull request by wershlak**
@drewhershey I undid the clang format commit and rebased test on master. There were some conflicts but mostly in news. I _think_ I resolved them successfully. We should be able to redo the formatting easy enough if we can get everything merged.

- You mentioned there was a bug somewhere you were dealing with. Can you resolve it here?

I should mention that we won't merge this but simply replace master with this branch. Let's chat about it.

### CODE REVIEW

**Review by drewhershey — APPROVED** [review]
I pulled the branch, compiled, and ran it and everything seems to be working fine as far as I can tell. I don't think we need to hold this PR up to get my limb code fix in before merging - the bug isn't gamebreaking by any means, so I can just make a separate PR for the fix once it's ready.

What's the next step for getting this finished up?

**Comment by cizra** [comment]
Shouldn't you `git fetch; git merge -s ours origin/master` first to resolve the conflicts, if you're replacing the master branch?

**Comment by wershlak** [comment]
Yeah exactly, except I removed the commit that applied the clang format since that was making the merge conflicts unmanageable. That probably makes the diff in the PR look worse. We’ll reapply that format once we fix things.I could alternately create a new branch “main” that is master minus the clang format and provide a PR comparing test to this new branch. This might look cleaner for review if you want?Sent from my iPhoneOn Nov 8, 2023, at 2:01 AM, Elmo Todurov ***@***.***> wrote:﻿
Shouldn't you git fetch; git merge -s ours origin/master first to resolve the conflicts, if you're replacing the master branch?

**Comment by cizra** [comment]
Hey, folks, I don't foresee I'll have the energy and attention to review this mammoth of a PR. If it works, and does what you want, I'll approve it :D

**Comment by drewhershey** [comment]
I'm pretty sure I speak for the others in saying I completely understand. We just wanted to make sure to include you before we merged something like this in case you had any objections and wanted to veto it for some reason, out of appreciation for all the work you've put into keeping the game alive over the years.

We've been running the live server off a branch containing this code for a year now, so it's been thoroughly play tested (though not unit tested 🥲) at least.

Thanks for taking the time to glance it over, hope you're doing well.

**Pull request merged**
