### PR TITLE
Made donations public

### PR DESCRIPTION
**Pull request by cizra**

### CODE REVIEW

**Comment by rmsr** [comment]
Donate supports the usual all.[item] and [num]*[item] so this could really blast the hell out of people's screens basically at random. Perhaps emit a single summary at the end of the donate command?

**Comment by rmsr** [comment]
@Hordeking why are you approving PRs that fail travis build...

**Comment by cizra** [comment]
What is it failing anyway?

**Comment by rmsr** [comment]
I think it was some kind of transient failure is on travis's end. When I rebased pr17 the optimized build failed after 7(!!!) hours. This PR didn't even have any text in the travis build log! I restarted the builds and so far so good.

**Comment by rmsr** [comment]
Updated #102 with my thoughts on the spamminess, so we can revisit later.

**Pull request merged**
